### ISSUE TITLE
PrusaSlicer 2.1.1

### ISSUE THREAD

**Issue by padigree** [koendv/prusa-slicer-raspberrypi#1]
Would like to see updated versions of Prusaslicer (e.g. 2.1.1 which includes the PrusaMini)

**Comment by koendv** [comment]
OK, noted. WIll be next year, though.

**Comment by koendv** [comment]
OK, Done. here's a build waiting for you. Check if it works.

Now you can do all of your 3d printing in raspberry: designing in openscad, slicing in prusa-slicer, checking the g-code in camotics. 

There's one thing you could do for me. In prusa-slicer you can easily choose your Prusa i3 mini as printer. But in camotics, when you go to Edit -> Settings -> Machine, there's no choice that says "Prusa". I'd be obliged if you could add a "Prusa" to camotics. 

Camotics machine models are text files in /usr/share/doc/camotics/machines/ .
